"""Agent templates (specs/03-chat-and-deploy.md: `GET /templates`, CD-1).

Each template supplies the starting `system_prompt` / `tools` / `files` for a
new agent's v1. `files` entries are `{name, content}` pairs (content is text,
written to disk by the caller and turned into the `{name, path_on_disk,
size}` shape that `AgentVersion.files` expects per specs/01-data-model.md).

`data-analyst` seeds `orders.csv` generated by `scripts/seed_demo.py`'s
deterministic generator (AC-CD-a: "files include orders.csv") and enables all
five tools.
"""
from __future__ import annotations

import csv
import io
import sys
from pathlib import Path
from typing import TypedDict

from app.tools import TOOL_NAMES

_SCRIPTS_DIR = Path(__file__).resolve().parent.parent.parent / "scripts"


class TemplateFile(TypedDict):
    name: str
    content: str


class Template(TypedDict):
    id: str
    label: str
    description: str
    system_prompt: str
    tools: list[str]
    files: list[TemplateFile]


def _generate_orders_csv_text() -> str:
    """Reuse scripts/seed_demo.py's deterministic generator so the template's
    orders.csv matches the demo seed data exactly (same seed, same rows).
    """
    sys.path.insert(0, str(_SCRIPTS_DIR))
    from seed_demo import generate_rows  # noqa: PLC0415 (lazy import by design)

    rows = generate_rows()
    fieldnames = ["order_id", "created_at", "region", "product", "list_price", "amount", "status"]
    buf = io.StringIO(newline="")
    writer = csv.DictWriter(buf, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow({k: row[k] for k in fieldnames})
    return buf.getvalue()


def _blank_template() -> Template:
    return {
        "id": "blank",
        "label": "Blank",
        "description": "An empty agent with no starting prompt, tools, or files.",
        "system_prompt": "You are a helpful assistant.",
        "tools": [],
        "files": [],
    }


def _data_analyst_template() -> Template:
    return {
        "id": "data-analyst",
        "label": "Data Analyst",
        "description": "Analyzes orders.csv: revenue, refunds, top products, and more.",
        "system_prompt": (
            "You are a data analyst. You have access to a sandbox containing "
            "orders.csv with columns: order_id, created_at, region, product, "
            "list_price, amount, status. Use the bash tool with pandas or "
            "shell commands to compute precise answers rather than guessing. "
            "Always state whether your figures exclude refunded orders when "
            "that matters to the question."
        ),
        "tools": list(TOOL_NAMES),
        "files": [{"name": "orders.csv", "content": _generate_orders_csv_text()}],
    }


def _repo_helper_template() -> Template:
    return {
        "id": "repo-helper",
        "label": "Repo Helper",
        "description": "Reads, edits, and explains code in a small workspace.",
        "system_prompt": (
            "You are a software engineering assistant. You have access to a "
            "sandbox workspace with tools to read, write, edit, and list "
            "files, and to run shell commands. Make minimal, correct changes "
            "and explain what you did."
        ),
        "tools": list(TOOL_NAMES),
        "files": [],
    }


def list_templates() -> list[Template]:
    return [_blank_template(), _data_analyst_template(), _repo_helper_template()]


def get_template(template_id: str) -> Template:
    for t in list_templates():
        if t["id"] == template_id:
            return t
    raise ValueError(f"unknown template: {template_id!r}")
